#!/usr/bin/python3
"""Module that factorize as many numbers as possible
 into a product of two smaller numbers."""
from sys import argv


FILE=$1
while read NUMBERS;
do
    factors=($(factor $NUMBERS))
    echo "$NUMBERS=$(($NUMBERS/${factors[1]}))*${factors[1]}"
done < $FILE	
